/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BackTest,
    BackTestFromJSON,
    BackTestToJSON,
    BackTestResponse,
    BackTestResponseFromJSON,
    BackTestResponseToJSON,
    BackTestRun,
    BackTestRunFromJSON,
    BackTestRunToJSON,
} from '../models';

export interface BackTestRequest {
    botJar?: Blob;
    backTestRequest?: string;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Create a back test
     * @param {Blob} [botJar] 
     * @param {string} [backTestRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    backTestRaw(requestParameters: BackTestRequest): Promise<runtime.ApiResponse<BackTestResponse>>;

    /**
     * Create a back test
     */
    backTest(requestParameters: BackTestRequest): Promise<BackTestResponse>;

    /**
     * 
     * @summary get backtest run list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getBackTestRunsRaw(): Promise<runtime.ApiResponse<Array<BackTestRun>>>;

    /**
     * get backtest run list
     */
    getBackTestRuns(): Promise<Array<BackTestRun>>;

    /**
     * 
     * @summary get backtest list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getBackTestsRaw(): Promise<runtime.ApiResponse<Array<BackTest>>>;

    /**
     * get backtest list
     */
    getBackTests(): Promise<Array<BackTest>>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Create a back test
     */
    async backTestRaw(requestParameters: BackTestRequest): Promise<runtime.ApiResponse<BackTestResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.botJar !== undefined) {
            formParams.append('botJar', requestParameters.botJar as any);
        }

        if (requestParameters.backTestRequest !== undefined) {
            formParams.append('backTestRequest', requestParameters.backTestRequest as any);
        }

        const response = await this.request({
            path: `/api/backtest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BackTestResponseFromJSON(jsonValue));
    }

    /**
     * Create a back test
     */
    async backTest(requestParameters: BackTestRequest): Promise<BackTestResponse> {
        const response = await this.backTestRaw(requestParameters);
        return await response.value();
    }

    /**
     * get backtest run list
     */
    async getBackTestRunsRaw(): Promise<runtime.ApiResponse<Array<BackTestRun>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/backtestrun`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BackTestRunFromJSON));
    }

    /**
     * get backtest run list
     */
    async getBackTestRuns(): Promise<Array<BackTestRun>> {
        const response = await this.getBackTestRunsRaw();
        return await response.value();
    }

    /**
     * get backtest list
     */
    async getBackTestsRaw(): Promise<runtime.ApiResponse<Array<BackTest>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/backtest`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BackTestFromJSON));
    }

    /**
     * get backtest list
     */
    async getBackTests(): Promise<Array<BackTest>> {
        const response = await this.getBackTestsRaw();
        return await response.value();
    }

}
