/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BackTestStatus {
    RUNNING = 'RUNNING',
    FINISHED = 'FINISHED',
    WAITING = 'WAITING',
    ERROR = 'ERROR',
    CANCEL = 'CANCEL'
}

export function BackTestStatusFromJSON(json: any): BackTestStatus {
    return BackTestStatusFromJSONTyped(json, false);
}

export function BackTestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackTestStatus {
    return json as BackTestStatus;
}

export function BackTestStatusToJSON(value?: BackTestStatus | null): any {
    return value as any;
}

