/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BackTestRun,
    BackTestRunFromJSON,
    BackTestRunFromJSONTyped,
    BackTestRunToJSON,
} from './';

/**
 * 
 * @export
 * @interface BackTestRunResponse
 */
export interface BackTestRunResponse {
    /**
     * 
     * @type {number}
     * @memberof BackTestRunResponse
     */
    totalBackTestRun: number;
    /**
     * 
     * @type {Array<BackTestRun>}
     * @memberof BackTestRunResponse
     */
    backTestRuns?: Array<BackTestRun>;
}

export function BackTestRunResponseFromJSON(json: any): BackTestRunResponse {
    return BackTestRunResponseFromJSONTyped(json, false);
}

export function BackTestRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackTestRunResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalBackTestRun': json['totalBackTestRun'],
        'backTestRuns': !exists(json, 'backTestRuns') ? undefined : ((json['backTestRuns'] as Array<any>).map(BackTestRunFromJSON)),
    };
}

export function BackTestRunResponseToJSON(value?: BackTestRunResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalBackTestRun': value.totalBackTestRun,
        'backTestRuns': value.backTestRuns === undefined ? undefined : ((value.backTestRuns as Array<any>).map(BackTestRunToJSON)),
    };
}


