/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BalanceDto
 */
export interface BalanceDto {
    /**
     * 
     * @type {number}
     * @memberof BalanceDto
     */
    time: number;
    /**
     * 
     * @type {number}
     * @memberof BalanceDto
     */
    value: number;
}

export function BalanceDtoFromJSON(json: any): BalanceDto {
    return BalanceDtoFromJSONTyped(json, false);
}

export function BalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': json['time'],
        'value': json['value'],
    };
}

export function BalanceDtoToJSON(value?: BalanceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
        'value': value.value,
    };
}


