/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CandleDto
 */
export interface CandleDto {
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    beginTime: number;
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    endTime: number;
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    open: number;
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    close: number;
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    high: number;
    /**
     * 
     * @type {number}
     * @memberof CandleDto
     */
    low: number;
}

export function CandleDtoFromJSON(json: any): CandleDto {
    return CandleDtoFromJSONTyped(json, false);
}

export function CandleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'beginTime': json['beginTime'],
        'endTime': json['endTime'],
        'open': json['open'],
        'close': json['close'],
        'high': json['high'],
        'low': json['low'],
    };
}

export function CandleDtoToJSON(value?: CandleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'beginTime': value.beginTime,
        'endTime': value.endTime,
        'open': value.open,
        'close': value.close,
        'high': value.high,
        'low': value.low,
    };
}


