/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrawdownDto
 */
export interface DrawdownDto {
    /**
     * 
     * @type {string}
     * @memberof DrawdownDto
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof DrawdownDto
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof DrawdownDto
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof DrawdownDto
     */
    endDate: string;
}

export function DrawdownDtoFromJSON(json: any): DrawdownDto {
    return DrawdownDtoFromJSONTyped(json, false);
}

export function DrawdownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawdownDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
        'startDate': json['startDate'],
        'endDate': json['endDate'],
    };
}

export function DrawdownDtoToJSON(value?: DrawdownDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'value': value.value,
        'startDate': value.startDate,
        'endDate': value.endDate,
    };
}


