/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnlineCreateResponse
 */
export interface OnlineCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof OnlineCreateResponse
     */
    ident?: string;
    /**
     * 
     * @type {string}
     * @memberof OnlineCreateResponse
     */
    onlineId?: string;
}

export function OnlineCreateResponseFromJSON(json: any): OnlineCreateResponse {
    return OnlineCreateResponseFromJSONTyped(json, false);
}

export function OnlineCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnlineCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ident': !exists(json, 'ident') ? undefined : json['ident'],
        'onlineId': !exists(json, 'onlineId') ? undefined : json['onlineId'],
    };
}

export function OnlineCreateResponseToJSON(value?: OnlineCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ident': value.ident,
        'onlineId': value.onlineId,
    };
}


