/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OnlineRequest,
    OnlineRequestFromJSON,
    OnlineRequestFromJSONTyped,
    OnlineRequestToJSON,
    TradePointDto,
    TradePointDtoFromJSON,
    TradePointDtoFromJSONTyped,
    TradePointDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface Online
 */
export interface Online {
    /**
     * 
     * @type {number}
     * @memberof Online
     */
    startTime: number;
    /**
     * 
     * @type {number}
     * @memberof Online
     */
    updatedTime: number;
    /**
     * 
     * @type {number}
     * @memberof Online
     */
    endTime: number;
    /**
     * 
     * @type {string}
     * @memberof Online
     */
    ident?: string;
    /**
     * 
     * @type {string}
     * @memberof Online
     */
    onlineId?: string;
    /**
     * 
     * @type {OnlineRequest}
     * @memberof Online
     */
    onlineRequest?: OnlineRequest;
    /**
     * 
     * @type {Array<TradePointDto>}
     * @memberof Online
     */
    tradePointDtos?: Array<TradePointDto>;
}

export function OnlineFromJSON(json: any): Online {
    return OnlineFromJSONTyped(json, false);
}

export function OnlineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Online {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': json['startTime'],
        'updatedTime': json['updatedTime'],
        'endTime': json['endTime'],
        'ident': !exists(json, 'ident') ? undefined : json['ident'],
        'onlineId': !exists(json, 'onlineId') ? undefined : json['onlineId'],
        'onlineRequest': !exists(json, 'onlineRequest') ? undefined : OnlineRequestFromJSON(json['onlineRequest']),
        'tradePointDtos': !exists(json, 'tradePointDtos') ? undefined : ((json['tradePointDtos'] as Array<any>).map(TradePointDtoFromJSON)),
    };
}

export function OnlineToJSON(value?: Online | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startTime': value.startTime,
        'updatedTime': value.updatedTime,
        'endTime': value.endTime,
        'ident': value.ident,
        'onlineId': value.onlineId,
        'onlineRequest': OnlineRequestToJSON(value.onlineRequest),
        'tradePointDtos': value.tradePointDtos === undefined ? undefined : ((value.tradePointDtos as Array<any>).map(TradePointDtoToJSON)),
    };
}


