/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlotDto
 */
export interface PlotDto {
    /**
     * 
     * @type {number}
     * @memberof PlotDto
     */
    pricePrecision: number;
    /**
     * 
     * @type {string}
     * @memberof PlotDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlotDto
     */
    color?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PlotDto
     */
    values?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PlotDto
     */
    style?: string;
}

export function PlotDtoFromJSON(json: any): PlotDto {
    return PlotDtoFromJSONTyped(json, false);
}

export function PlotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pricePrecision': json['pricePrecision'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'values': !exists(json, 'values') ? undefined : json['values'],
        'style': !exists(json, 'style') ? undefined : json['style'],
    };
}

export function PlotDtoToJSON(value?: PlotDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pricePrecision': value.pricePrecision,
        'name': value.name,
        'color': value.color,
        'values': value.values,
        'style': value.style,
    };
}


