/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradePointDto
 */
export interface TradePointDto {
    /**
     * 
     * @type {number}
     * @memberof TradePointDto
     */
    tradeTime: number;
    /**
     * 
     * @type {string}
     * @memberof TradePointDto
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof TradePointDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof TradePointDto
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof TradePointDto
     */
    pnl: number;
}

export function TradePointDtoFromJSON(json: any): TradePointDto {
    return TradePointDtoFromJSONTyped(json, false);
}

export function TradePointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradePointDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tradeTime': json['tradeTime'],
        'price': json['price'],
        'status': json['status'],
        'type': json['type'],
        'pnl': json['pnl'],
    };
}

export function TradePointDtoToJSON(value?: TradePointDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tradeTime': value.tradeTime,
        'price': value.price,
        'status': value.status,
        'type': value.type,
        'pnl': value.pnl,
    };
}


